export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

export const SEND_FORWARD_BACKWARD = 'SEND_FORWARD_BACKWARD';
export const SEND_LEFT_RIGHT = 'SEND_LEFT_RIGHT';
export const SEND_START = 'SEND_START';
export const SEND_STOP = 'SEND_STOP';
export const SEND_PLAY = 'SEND_PLAY';
